---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: nginx-deployment-prod
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: nginx-deployment-prod
      spec: 
        containers: 
            image: "nginx:1.7.9"
            name: nginx-deployment-prod
            ports:
            - containerPort: 80

