---
apiVersion: v1
kind: Pod # definition
metadata:
  name : nginx-2 # name of the pod
  labels:
     app: nginx-2
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
      - containerPort: 80

